### PR TITLE
Fix installations for cuelang version >= 3.0.0

### PR DESCRIPTION
**Pull request by vyas-n**
This should resolve issue #10

### CODE REVIEW

**Comment by smorimoto** [comment]
We need to support previous versions as well.

**Comment by vyas-n** [comment]
Sorry @smorimoto, I didn't read through the cuelang releases to check if past releases had different casing.

I've updated the PR. Would this approach work?

**Comment by smorimoto** [comment]
At least the test tells us it failed.

**Comment by vyas-n** [comment]
Sorry about that, I'll rework the PR

**Comment by smorimoto** [comment]
By the way, please note that there are 2 different PRs for the same goal: #11 #15

**Pull request closed without merging**
