### PR TITLE
Update address to new cue-lang/cue home

### LINKED ISSUE #16: Track new CUE home
Re: https://github.com/cue-lang/cue/issues/1078

Should be an easy replacement in the url, I don't _think_ we'll need to support both addresses

### PR DESCRIPTION
**Pull request by spencergilbert**
Closes #16

### CODE REVIEW

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Thanks @spencergilbert!

**Comment by spencergilbert** [comment]
👍 not sure why the macos test fails, it seems to be working locally - happy to try and figure it out if it persists

**Comment by smorimoto** [comment]
Yeah, indeed it’s very weird… If you have some time, please investigate and open a PR to fix the issue 🙂

**Comment by spencergilbert** [comment]
Seems happier on the schedule pipeline

**Comment by smorimoto** [comment]
I just re-triggered and the weird error seems to have been solved. Hrm, anyway! Thank you for letting me know that!

**Pull request merged**
