### PR TITLE
fix cue didn't work

### PR DESCRIPTION
**Pull request by NeoHsu**
Hi,

I look this [issue #10](https://github.com/asdf-community/asdf-cue/issues/10),

And I try to install cue on OSX, I get same issue that cue plugin didn't work,

so I modify build flow and installer cue plugin.

I hope to help this plugin.

thanks !

### CODE REVIEW

**Comment by NeoHsu** [comment]
Hi @smorimoto,
please check this PR, thanks.
I hope to help this plugin be better !

**Comment by smorimoto** [comment]
As you know, the last two days including today are holidays. I can see this tomorrow.

**Comment by smorimoto** [comment]
Well, I just took a look at some of the holidays, but there are too many changes that are not directly related. I will fix everything including that later.

**Comment by smorimoto** [comment]
Hmm, does this work with 0.2.2?

**Comment by NeoHsu** [comment]
Hi @smorimoto,
I updated this PR and I fixed different filename issue of cue release files,
I changed to get download filename method from string combination to checksums file.
I think this solution will work be better. 
thanks.

**Comment by smorimoto** [comment]
What about getting them from the GitHub API? It sounds quite unstable in that way.

**Comment by smorimoto** [comment]
By the way, please note that there are 2 different PRs for the same goal: #11 #15

**Comment by NeoHsu** [comment]
Sure, I already changed the resource from checksums file to GitHub API.
Hi @smorimoto, please  check this PR again, thanks.
I want to fix this issue ASAP.

**Comment by smorimoto** [comment]
Well, we basically don't allow for more system dependencies, so using something like jq is not recommended.

**Comment by smorimoto** [comment]
It's good to fix quickly, but fixing reliably is more important in general :)

**Comment by NeoHsu** [comment]
Hi @smorimoto ,

I'm sorry that I was a little insensitive for system dependencies.

I already changed JSON parser from jq to grep/awk/sed command and I think this solution will work be better.
I'm agree with you on that "fixing reliably is more important in general".

But I can’t believe that this plugin didn't work since v0.3.0 and nobody want to fix this.
I only hope to fix this issue, maybe you don't think so.

Thanks for your suggest.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Looks good, thanks @NeoHsu! Hrm, I still don't get why you felt that, but I appreciate your contribution anyway! Sorry for the late review, I was a little busy between Cambridge/Paris and Japan.

**Comment by smorimoto** [comment]
Also, don't hesitate to join the asdf-cue team if you want to maintain this plugin continuously! By making such changes, you can create the tem and then add yourself to the team: https://github.com/asdf-community/infrastructure/commit/d013acf2c68468531cd25e04f52ef04b5591a06b

**Pull request merged**
